name: Trigger Jenkins Pipeline

on: [push]

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST http://3.90.212.36:8080/job/note-app/build
